name: boticas_toty_farma_02
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  geolocator: ^11.0.0
  http: ^1.2.1
  google_maps_flutter: ^2.6.0
  image_picker: ^1.0.7
  firebase_storage: ^12.4.6
  google_fonts: ^6.0.0
  intl: ^0.18.1
  sensors_plus: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:                  
  android: true
  ios: true
  image_path: assets/images/icon.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/loading_botica.jpeg
    - assets/images/icon.png
    - assets/images/moto.jpeg